# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_monitor.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QTextBrowser,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(960, 737)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(230, 10, 471, 121))
        font = QFont()
        font.setPointSize(45)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(140, 110, 261, 131))
        font1 = QFont()
        font1.setPointSize(40)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.current_rpm = QLabel(self.centralwidget)
        self.current_rpm.setObjectName(u"current_rpm")
        self.current_rpm.setGeometry(QRect(410, 100, 181, 131))
        self.current_rpm.setFont(font1)
        self.current_rpm.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(600, 120, 151, 101))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(160, 200, 241, 101))
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_current = QLabel(self.centralwidget)
        self.label_current.setObjectName(u"label_current")
        self.label_current.setGeometry(QRect(430, 210, 161, 71))
        self.label_current.setFont(font1)
        self.label_current.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(610, 210, 61, 71))
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(310, 540, 231, 101))
        self.label_8.setFont(font1)
        self.label_final_okng = QLabel(self.centralwidget)
        self.label_final_okng.setObjectName(u"label_final_okng")
        self.label_final_okng.setGeometry(QRect(570, 550, 91, 71))
        self.label_final_okng.setFont(font1)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(690, 370, 151, 101))
        self.label_10.setFont(font1)
        self.lable_final_rpm = QLabel(self.centralwidget)
        self.lable_final_rpm.setObjectName(u"lable_final_rpm")
        self.lable_final_rpm.setGeometry(QRect(510, 360, 141, 131))
        self.lable_final_rpm.setFont(font1)
        self.lable_final_rpm.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(560, 470, 91, 71))
        self.label_12.setFont(font1)
        self.label_12.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(700, 470, 61, 71))
        self.label_13.setFont(font1)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(150, 460, 361, 101))
        self.label_14.setFont(font1)
        self.label_14.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(130, 360, 401, 131))
        self.label_15.setFont(font1)
        self.widget_box = QWidget(self.centralwidget)
        self.widget_box.setObjectName(u"widget_box")
        self.widget_box.setGeometry(QRect(110, 370, 761, 261))
        self.widget_box.setAutoFillBackground(False)
        self.widget_box.setStyleSheet(u"background:rgb(0, 255, 0)")
        self.widget_box_upper = QWidget(self.centralwidget)
        self.widget_box_upper.setObjectName(u"widget_box_upper")
        self.widget_box_upper.setGeometry(QRect(180, 130, 631, 161))
        self.widget_box_upper.setAutoFillBackground(False)
        self.widget_box_upper.setStyleSheet(u"border: 1px solid red")
        self.textBrowser = QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(260, 640, 161, 51))
        font2 = QFont()
        font2.setPointSize(20)
        self.textBrowser.setFont(font2)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(610, 290, 61, 71))
        self.label_16.setFont(font1)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 280, 241, 101))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_voltage = QLabel(self.centralwidget)
        self.label_voltage.setObjectName(u"label_voltage")
        self.label_voltage.setGeometry(QRect(430, 290, 161, 71))
        self.label_voltage.setFont(font1)
        self.label_voltage.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(550, 640, 81, 51))
        self.lineEdit_load = QLineEdit(self.centralwidget)
        self.lineEdit_load.setObjectName(u"lineEdit_load")
        self.lineEdit_load.setGeometry(QRect(430, 640, 113, 51))
        self.lineEdit_load.setFont(font2)
        self.lineEdit_load.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.widget_box.raise_()
        self.widget_box_upper.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.current_rpm.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_current.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_final_okng.raise_()
        self.label_10.raise_()
        self.lable_final_rpm.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.textBrowser.raise_()
        self.label_16.raise_()
        self.label_6.raise_()
        self.label_voltage.raise_()
        self.pushButton.raise_()
        self.lineEdit_load.raise_()
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">\uc131\ub2a5\uac80\uc0ac \ubaa8\ub2c8\ud130</span></p></body></html>", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\ud68c\uc804\uc218:", None))
        self.current_rpm.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">0</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uc804\ub958:", None))
        self.label_current.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">0</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\uc885\ud569\ud310\uc815:", None))
        self.label_final_okng.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">OK</span></p></body></html>", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"RPM", None))
        self.lable_final_rpm.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">0</span></p></body></html>", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">0</span></p></body></html>", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\ucd5c\uc885\uce21\uc815\uc804\ub958:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"\ucd5c\uc885\uce21\uc815\ud68c\uc804\uc218:", None))
        self.textBrowser.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'\ub9d1\uc740 \uace0\ub515'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\uc815\uaca9\ubd80\ud558\uc728:</p></body></html>", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\uc778\uac00\uc804\uc555:", None))
        self.label_voltage.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#ff0000;\">0</span></p></body></html>", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\ubd80\ud558\uc728\n"
"\uc800\uc7a5", None))
    # retranslateUi

